[package]
name = "proxy6-rs"
version = "0.1.0"
edition = "2024"

[lib]
name = "proxy6"
path = "src/lib.rs"

[dependencies]
reqwest = "0.12.27"
serde = "1.0.228"
serde_json = "1.0.146"
thiserror = "2.0.17"
